
// Common prefix
export const PREFIX_LOADING = "_LOADING";
export const PREFIX_OK = "_OK";
export const PREFIX_FAILED = "_FAILED";
export const PREFIX_TIME_OUT = "_TIME_OUT";
export const PREFIX_GET = "GET";
export const PREFIX_POST = "POST";
export const PREFIX_PUT = "PUT";
export const PREFIX_DELETE = "DELETE";

export const RESET_ACTION_STATUS = "FREE";

// Actions constant
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_OK = 'FETCH_EVENTS_OK';
export const FETCH_EVENTS_FAILED = 'FETCH_EVENTS_FAILED';
export const FETCH_EVENTS_TIME_OUT = 'FETCH_EVENTS_TIME_OUT';

export const FETCH_ACTIONS = 'FETCH_ACTIONS';
export const FETCH_ACTIONS_OK = 'FETCH_ACTIONS_OK';
export const FETCH_ACTIONS_FAILED = 'FETCH_ACTIONS_FAILED';
export const FETCH_ACTIONS_TIME_OUT = 'FETCH_ACTIONS_TIME_OUT';

export const DELETE_ACTION = 'DELETE_ACTION';
export const DELETE_ACTION_OK = 'DELETE_ACTION_OK';
export const DELETE_ACTION_FAILED = 'DELETE_ACTION_FAILED';
export const DELETE_ACTION_TIME_OUT = 'DELETE_ACTION_TIME_OUT';

// Practical exam
export const FETCH_PRACTICAL_EXAMS = 'FETCH_PRACTICAL_EXAMS';
export const FETCH_PRACTICAL_EXAMS_OK = 'FETCH_PRACTICAL_EXAMS_OK';
export const FETCH_PRACTICAL_EXAMS_FAILED = 'FETCH_PRACTICAL_EXAMS_FAILED';
export const FETCH_PRACTICAL_EXAMS_TIME_OUT = 'FETCH_PRACTICAL_EXAMS_TIME_OUT';

// View files
export const VIEW_CODE_FILES = 'VIEW_CODE_FILES';
export const VIEW_CODE_FILES_OK = 'VIEW_CODE_FILES_OK';
export const VIEW_CODE_FILES_FAILED = 'VIEW_CODE_FILES_FAILED';
export const VIEW_CODE_FILES_TIME_OUT = 'VIEW_CODE_FILES_TIME_OUT';

// Subject init
export const FETCH_SUBJECT_INIT = 'FETCH_SUBJECT_INIT';
export const FETCH_SUBJECT_INIT_OK = 'FETCH_SUBJECT_INIT_OK';
export const FETCH_SUBJECT_INIT_FAILED = 'FETCH_SUBJECT_INIT_FAILED';
export const FETCH_SUBJECT_INIT_TIME_OUT = 'FETCH_SUBJECT_INIT_TIME_OUT';

// Subject full info
export const FETCH_SUBJECT_FULLINFO = 'FETCH_SUBJECT_FULLINFO';
export const FETCH_SUBJECT_FULLINFO_OK = 'FETCH_SUBJECT_FULLINFO_OK';
export const FETCH_SUBJECT_FULLINFO_FAILED = 'FETCH_SUBJECT_FULLINFO_FAILED';
export const FETCH_SUBJECT_FULLINFO_TIME_OUT = 'FETCH_SUBJECT_FULLINFO_TIME_OUT';

export const CREATE_PRACTICAL_EXAMS = 'CREATE_PRACTICAL_EXAMS';
export const CREATE_PRACTICAL_EXAMS_OK = 'CREATE_PRACTICAL_EXAMS_OK';
export const CREATE_PRACTICAL_EXAMS_FAILED = 'CREATE_PRACTICAL_EXAMS_FAILED';
export const CREATE_PRACTICAL_EXAMS_TIME_OUT = 'CREATE_PRACTICAL_EXAMS_TIME_OUT';


export const DELETE_PRACTICAL_EXAMS = 'DELETE_PRACTICAL_EXAMS';
export const DELETE_PRACTICAL_EXAMS_OK = 'DELETE_PRACTICAL_EXAMS_OK';
export const DELETE_PRACTICAL_EXAMS_FAILED = 'DELETE_PRACTICAL_EXAMS_FAILED';
export const DELETE_PRACTICAL_EXAMS_TIME_OUT = 'DELETE_PRACTICAL_EXAMS_TIME_OUT';

// test script
export const FETCH_TEST_SCRIPT= 'FETCH_TEST_SCRIPT';
export const FETCH_TEST_SCRIPT_OK = 'FETCH_TEST_SCRIPT_OK';
export const FETCH_TEST_SCRIPT_FAILED = 'FETCH_TEST_SCRIPT_FAILED';
export const FETCH_TEST_SCRIPT_TIME_OUT = 'FETCH_TEST_SCRIPT_TIME_OUT';

export const GET_TEST_SCRIPT= 'GET_TEST_SCRIPT';
export const GET_TEST_SCRIPT_OK = 'GET_TEST_SCRIPT_OK';
export const GET_TEST_SCRIPT_FAILED = 'GET_TEST_SCRIPT_FAILED';
export const GET_TEST_SCRIPT_TIME_OUT = 'GET_TEST_SCRIPT_TIME_OUT';

export const CREATE_TEST_SCRIPT = 'CREATE_TEST_SCRIPT';
export const CREATE_TEST_SCRIPT_OK = 'CREATE_TEST_SCRIPT_OK';
export const CREATE_TEST_SCRIPT_FAILED = 'CREATE_TEST_SCRIPT_FAILED';
export const CREATE_TEST_SCRIPT_TIME_OUT = 'CREATE_TEST_SCRIPT_TIME_OUT';

export const UPDATE_TEST_SCRIPT = 'UPDATE_TEST_SCRIPT';
export const UPDATE_TEST_SCRIPT_OK = 'UPDATE_TEST_SCRIPT_OK';
export const UPDATE_TEST_SCRIPT_FAILED = 'UPDATE_TEST_SCRIPT_FAILED';
export const UPDATE_TEST_SCRIPT_TIME_OUT = 'UPDATE_TEST_SCRIPT_TIME_OUT';


export const DELETE_TEST_SCRIPT = 'DELETE_TEST_SCRIPT';
export const DELETE_TEST_SCRIPT_OK = 'DELETE_TEST_SCRIPT_OK';
export const DELETE_TEST_SCRIPT_FAILED = 'DELETE_TEST_SCRIPT_FAILED';
export const DELETE_TEST_SCRIPT_TIME_OUT = 'DELETE_TEST_SCRIPT_TIME_OUT';

export const GET_DUPLICATED_STUDENT_LIST = 'GET_DUPLICATED_STUDENT_LIST';
export const GET_DUPLICATED_STUDENT_LIST_OK = 'GET_DUPLICATED_STUDENT_LIST_OK';
export const GET_DUPLICATED_STUDENT_LIST_FAILED = 'GET_DUPLICATED_STUDENT_LIST_FAILED';
export const GET_DUPLICATED_STUDENT_LIST_TIME_OUT = 'GET_DUPLICATED_STUDENT_LIST_TIME_OUT';

export const GET_GITHUB_RESULT = 'GET_GITHUB_RESULT';
export const GET_GITHUB_RESULT_OK = 'GET_GITHUB_RESULT_OK';
export const GET_GITHUB_RESULT_FAILED = 'GET_GITHUB_RESULT_FAILED';
export const GET_GITHUB_RESULT_TIME_OUT = 'GET_GITHUB_RESULT_TIME_OUT';

export const GET_PARAM_TYPE = 'GET_PARAM_TYPE';
export const GET_PARAM_TYPE_OK = 'GET_PARAM_TYPE_OK';
export const GET_PARAM_TYPE_FAILED = 'GET_PARAM_TYPE_FAILED';
export const GET_PARAM_TYPE_TIME_OUT = 'GET_PARAM_TYPE_TIME_OUT';

// End point 
export const API_URL = 'http://localhost:2021/api';
export const API_URL_DUMMY = 'http://localhost:4000'
export const END_POINT_EVENTS = "action/subject";
export const END_POINT_SUBJECTS = "subjects";
export const END_POINT_CLASSES = "classes";

export const END_POINT_LECTURER = "lecturers";
export const END_POINT_SUBMISSION_FILE = "submission/file";
export const END_POINT_PRACTICAL_EXAMS = "practical-exam";
export const END_POINT_PARAM_TYPE  = "param-type";
export const END_POINT_CLASSES_SCRIPTS = "classes-scripts";
export const END_POINT_POST_TESTSCRIPT = "scripts";
export const END_POINT_DOWNLOAD_TESTSCRIPT = "scripts/download";
export const END_POINT_DOWNLOAD_TESTDATA = "testData/download";
export const END_POINT_DOWNLOAD_DOCUMENT = "documents/download";
export const END_POINT_DOWNLOAD_TEMPLATE_QUESTION = "templateQuestion/download";
export const END_POINT_DOWNLOAD_TEMPLATE_QUESTION_TEMPLATE = "templateQuestionTemplate/download";
export const END_POINT_DOWNLOAD_DATABASE = "database/download";
export const END_POINT_GET_TESTSCRIPT_BY_SUBJECTID = "scripts/subject";
export const END_POINT_TESTSCRIPTS = "testScript";
export const END_POINT_LIST_ACTION = "actions";
export const END_POINT_ACTION = "actions";
export const END_POINT_DUPLICATEDCODE_STUDENT_LIST = "practical-exam/check-code/result";
export const END_POINT_GITHUB_RESULT = "practical-exam/check-code/resultOnline";


// API Method
export const METHOD_GET = "GET";
export const METHOD_POST = "POST";

// Test Script anotations
export const ANOTATION_TEST_JAVA = "@Test";
export const ANOTATION_ORDER_JAVA = "@Order"
export const ANOTATION_TEST_CSHARP = "[TestMethod()]";


export const generateEndPoint = (...params) => {
    let fullEnpoint = "";
    for (let i = 0; i < params.length; i++) {
        fullEnpoint += params[i] + "/";
    }
    return fullEnpoint;
}

// message
export const MSG_EMPTY_SCRIPT_LIST = "No Test Script Available Now";